### ISSUE TITLE
How you started programming

### ISSUE THREAD

**Issue by lewiscowper** [turing-incomplete/turing-incomplete#123]
I guess it's come up a few times. But it'd be really cool to have everyone's starting story, and what they feel the most important thing that they learned in those early days, or what made them think. Yes, this is exactly what I want to be doing.

**Comment by ignu** [comment]
This was basically our third episode http://turing.cool/3/ 

It might be a good topic to revisit though!

**Comment by lewiscowper** [comment]
Ah, serves me right for not going through the archives. No worries. Will DL and listen. :+1:
