### ISSUE TITLE
the algebra and calculus of algebraic data types

### ISSUE THREAD

**Issue by joelburget** [turing-incomplete/turing-incomplete#131]
@pselle suggested I could come on the show. Perhaps talking about [my article](https://codewords.recurse.com/issues/three/algebra-and-calculus-of-algebraic-data-types) on algebraic data types.

I would also love to talk about
* living and working in Asia / Indonesia
* my [main project](http://pigment.io)

**Comment by pselle** [comment]
Hey @joelburget remember when we talked about talking about this? Interested in doing that soon? :) Our current regular recording time is Wednesdays at 11am Eastern.

**Comment by joelburget** [comment]
Hey, I am interested! I'm not available this Weds, but can probably do most any other.

**Comment by pselle** [comment]
Next week, 4/20?

**Comment by joelburget** [comment]
Yes that works for me

**Comment by pselle** [comment]
Sent you a calendar invite! My Skype is pamelaselle if you want to add me on there.

**Comment by joelburget** [comment]
Accepted. Looking forward to it!

**Comment by pselle** [comment]
Closing since we recorded + shipped :)
