### ISSUE TITLE
Sound levels

### ISSUE THREAD

**Issue by mackenza** [turing-incomplete/turing-incomplete#151]
I am fairly new to TI but am liking it so far. I mostly listen to it in the car and so background noise may be tainting my experience but I find that one of the voices (I think it's Len but not entirely sure) is very low when compared to Pam and Justin's. I also have some trouble with Jearvon's voice level. 

Perhaps check their levels and/or possibly enhance their voices with some post processing? It may not be a volume thing so much as a tone thing. 

Thanks and keep up the good work.

**Comment by iamjarvo** [comment]
Thanks for the feedback! We will experiment with our settings.
