### ISSUE TITLE
What is the name of the font from the last episode?

### ISSUE THREAD

**Issue by ulrikaugustsson** [turing-incomplete/turing-incomplete#167]
Jearvon picked a font last episode but I can't find it and it's not in the picks. Do you have the name of it? Or maybe even a link?

Thanks for a great show!

**Comment by justincampbell** [comment]
I'm pretty sure it's Fira Mono: http://mozilla.github.io/Fira/

Sorry about the shownotes not being accurate, we'll work on it. Thanks!!!

**Comment by iamjarvo** [comment]
Thanks for linking @justincampbell.

There is also this: https://github.com/tonsky/FiraCode (ligatures)
