### ISSUE TITLE
Turing Incomplete not on Google Play

### ISSUE THREAD

**Issue by belcherj** [turing-incomplete/turing-incomplete#183]
You need to point Google to the RSS feed:  https://play.google.com/music/podcasts/publish

**Comment by justincampbell** [comment]
Thanks! I tried to add it, but got the following error:

![](https://s3.amazonaws.com/f.cl.ly/items/0z341P3Y2n1t0C3T2L1o/Screen%20Shot%202016-07-20%20at%205.43.59%20PM.png)

But it appears that we have these fields:

```xml
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:media="http://search.yahoo.com/mrss/" version="2.0">
  <channel>
    <title>Turing-Incomplete</title>
    <description>A Podcast About Programming</description>
    <copyright>2014-2016 Turing-Incomplete</copyright>
    <language>en-us</language>
    <link>http://feeds.feedburner.com/Turing-Incomplete</link>
    <image>
      <link>http://feeds.feedburner.com/Turing-Incomplete</link>
      <title>Turing-Incomplete</title>
      <url>http://turing.cool/cover-art-512.png</url>
    </image>
    <itunes:author>Turing-Incomplete</itunes:author>
    <itunes:email>podcast@turing.cool</itunes:email>
    <itunes:explicit>no</itunes:explicit>
    <itunes:image href="http://turing.cool/cover-art-1400.png"/>
    <itunes:summary>A Podcast About Programming</itunes:summary>
    <itunes:category text="Technology">
      <itunes:category text="Software How-To"/>
      # ...
```

Is `<rss><channel>` the correct place for them?

**Comment by belcherj** [comment]
Hmmm, I have no idea how to proceed.  Here is the sample from Goog:
`<?xml version="1.0" encoding="UTF-8"?>

<rss xmlns:googleplay="http://www.google.com/schemas/play-podcasts/1.0" version="2.0">

<channel>

<title>The Unknown Podcast</title>

<link>http://sample.com/podcasts/unknown/index.html</link>

<language>en-us</language>

<copyright>℗ 2025 Unknown Podcaster Corp</copyright>

<googleplay:author>Unannounced Podcaster</googleplay:author>

<googleplay:description>The Unknown Podcast will look at all the things that are unknown or unknowable. Find us on Google Play Music!</googleplay:description>

<description>The Unknown Podcast will look at all the things that are unknown or unknowable.</description>

<googleplay:email>unknown-podcast@sample.com</googleplay:email>

<googleplay:image href="http://sample.com/podcasts/unknown/UnknownLargeImage.jpg" />

<googleplay:category text="Technology"/>

<item>

<title>What's out there?</title>

<googleplay:author>Engima</googleplay:author>

<googleplay:description>We look at all the things that are out there that we'd like to know.</googleplay:description>

<googleplay:image href="http://sample.com/podcasts/unknown/Episode1.jpg" />

<enclosure url="http://sample.com/podcasts/UnknownPodcastEpisode1.mp3" length="2320111" type="audio/mpeg" />

<guid>http://sample.com/podcasts/UnknownPodcastEpisode1.mp3</guid>

<pubDate>Mon, 29 Jun 2015 19:00:00 GMT</pubDate>

</item>

<item>

<title>What can we know, really?</title>

<googleplay:author>The everyman</googleplay:author>

<googleplay:description>And then we follow up on last week's podcast to examine what can and cannot be known.</googleplay:description>

<googleplay:image href="http://sample.com/podcasts/unknown/Episode2.jpg" />

<enclosure url="http://sample.com/podcasts/UnknownPodcastEpisode2.m4a" length="6421543" type="audio/x-m4a" />

<guid>http://sample.com/podcasts/UnknownPodcastEpisode2.m4a</guid>

<pubDate>Mon, 6 Jul 2015 19:00:00 GMT</pubDate>

</item>

</channel>

</rss>`

**Comment by justincampbell** [comment]
Adding the `googleplay:` tags seems to have fixed it! It is not under review. Thanks @belcherj!
