### ISSUE TITLE
Editors

### ISSUE THREAD

**Issue by mattgreen** [turing-incomplete/turing-incomplete#56]
I know this is a preference, but if you could get a real Vim/Emacs debate going it'd be interesting I think. (I'm hoping for a die-hard person on each side to make it even.) We tend to hear one side or the other in particular communities. It seems like Emacs tends to be bigger in FP communities, and Vim in more traditional programming language communities.

**Comment by zeusdeux** [comment]
@pselle We could do this!

I am down to take emacs' side (both for traditional languages like JS and for FP languages like Haskell/Clojure).

**Comment by pselle** [comment]
Yeah @zeusdeux sounds good to me!
