### ISSUE TITLE
Format text version of show notes so they're not terrible.

### ISSUE THREAD

**Issue by ignu** [turing-incomplete/turing-incomplete#65]
![https://dl.dropbox.com/s/ksyig9zjgzw1ff0/Screenshot%202014-09-17%2009.10.48.png?dl=0](https://dl.dropbox.com/s/ksyig9zjgzw1ff0/Screenshot%202014-09-17%2009.10.48.png?dl=0)

**Comment by pselle** [comment]
Closing as stale
